// <auto-generated />
using System;
using ICY.Home.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ICY.Home.API.Migrations
{
    [DbContext(typeof(GerenciadorDeTimesPokemonContext))]
    [Migration("20241017040745_AjusteLinha")]
    partial class AjusteLinha
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ICY.Home.API.Models.Pokemons", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("TiposSerializados")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("condicaoEvolucao")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("idPokemoEvolucao")
                        .HasColumnType("int");

                    b.Property<int>("levelEvolucao")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("id");

                    b.ToTable("Pokemons");
                });
#pragma warning restore 612, 618
        }
    }
}
